const countryList = {
  
    ARS: "AR",
    AUD: "AU",
    BGN: "BG",
    BRL: "BR",
    CAD: "CA",
    CHF: "CH",
    CNY: "CN",
    CYP: "CY",
    CZK: "CZ",
    DKK: "DK",
    DZD: "DZ",
    EUR: "FR",
    GBP: "GB",
    HKD: "HK",
    HRK: "HR",
    HUF: "HU",
    IDR: "ID",
    ILS: "IL",
    INR: "IN",
    ISK: "IS",
    JPY: "JP",
    KRW: "KR",
    LTL: "LT",
    LVL: "LV",
    MAD: "MA",
    MTL: "MT",
    MXN: "MX",
    MYR: "MY",
    NZD: "NZ",
    PHP: "PH",
    PLN: "PL",
    RON: "RO",
    RUB: "RU",
    SEK: "SE",
    SGD: "SG",
    SKK: "SK",
    THB: "TH",
    TRY: "TR",
    TWD: "TW",
    USD: "US",
    ZAR: "ZA",
   
  };